//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueenLand.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class homecat
    {
        public int id { get; set; }
        public string homebigcat { get; set; }
        public string homecat1 { get; set; }
    }
}
