//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueenLand.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class homecatitem
    {
        public int id { get; set; }
        public string homebigcat { get; set; }
        public string homecat { get; set; }
        public string title { get; set; }
        public Nullable<byte> isimage { get; set; }
        public string link { get; set; }
        public Nullable<byte> islinkfile { get; set; }
    }
}
